# Generated by Django 4.0.6 on 2023-04-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateTest', '0012_student_correct_student_incorrect_student_unanswered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='unanswered',
            field=models.IntegerField(default=0),
        ),
    ]
